name: Release

on:
  push:
    branches: [ main ]

jobs:
  check-build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

  steps:
    - uses: actions/checkout@v2
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: 15
    - name: install rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
    - name: install webkit2gtk
      run: |
        sudo apt-get update
        sudo apt-get install -y webkit2gtk-4.0
    - name: yarn setup
      run: yarn
    - name: frontend build distribution
      run: yarn build
    - name: install tauri
      run: cargo install tauri-bundler --force
    - name: build tauri app
      run: tauri build

  create-release:
    needs: check-build
    runs-on: ubuntu-latest
    outputs:
      RELEASE_UPLOAD_URL: ${{ steps.create_tauri_release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
          with:
            node-version: 15
      - name: create release
        id: create_tauri_release
        uses: jbolda/create-release@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ matrix.package.name }}-v${{ env.PACKAGE_VERSION }}
          release_name: 'Release lester app v${{ env.PACKAGE_VERSION }}'
          body: 'See the assets to download this version and install.'
          draft: true
          prerelease: false